### ISSUE TITLE
Why is C++ infinitely better than GD script?

### ISSUE THREAD

**Issue by tommy4111** [NicholasConnors/Minecraft-Clone#7]
Sorry for asking question here.

**Comment by xen-42** [comment]
Better simply in terms of performance. Generally I've heard it's about 60x faster than Godot script. The trade-off is that gdscript is much easier to use. Personally I like the happy middle ground of c#: it's about 10x than Godot script but not as hard to learn as C++

**Comment by tommy4111** [comment]
Thanks for the input.  Yikes 60x, I'll have to learn C++ then 😭 

I wonder the performance of GD in 2D.

**Comment by xen-42** [comment]
No worries. And it's only an issue sometimes, you can find ways to optimize GD script code to make it run smoothly. Especially for 2D which is naturally faster than 3D it's pretty good
